# This file has been generated by node2nix 1.11.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@formatjs/ecma402-abstract-1.11.4" = {
      name = "_at_formatjs_slash_ecma402-abstract";
      packageName = "@formatjs/ecma402-abstract";
      version = "1.11.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@formatjs/ecma402-abstract/-/ecma402-abstract-1.11.4.tgz";
        sha512 = "EBikYFp2JCdIfGEb5G9dyCkTGDmC57KSHhRQOC3aYxoPWVZvfWCDjZwkGYHN7Lis/fmuWl906bnNTJifDQ3sXw==";
      };
    };
    "@formatjs/fast-memoize-1.2.1" = {
      name = "_at_formatjs_slash_fast-memoize";
      packageName = "@formatjs/fast-memoize";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@formatjs/fast-memoize/-/fast-memoize-1.2.1.tgz";
        sha512 = "Rg0e76nomkz3vF9IPlKeV+Qynok0r7YZjL6syLz4/urSg0IbjPZCB/iYUMNsYA643gh4mgrX3T7KEIFIxJBQeg==";
      };
    };
    "@formatjs/icu-messageformat-parser-2.1.0" = {
      name = "_at_formatjs_slash_icu-messageformat-parser";
      packageName = "@formatjs/icu-messageformat-parser";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@formatjs/icu-messageformat-parser/-/icu-messageformat-parser-2.1.0.tgz";
        sha512 = "Qxv/lmCN6hKpBSss2uQ8IROVnta2r9jd3ymUEIjm2UyIkUCHVcbUVRGL/KS/wv7876edvsPe+hjHVJ4z8YuVaw==";
      };
    };
    "@formatjs/icu-skeleton-parser-1.3.6" = {
      name = "_at_formatjs_slash_icu-skeleton-parser";
      packageName = "@formatjs/icu-skeleton-parser";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@formatjs/icu-skeleton-parser/-/icu-skeleton-parser-1.3.6.tgz";
        sha512 = "I96mOxvml/YLrwU2Txnd4klA7V8fRhb6JG/4hm3VMNmeJo1F03IpV2L3wWt7EweqNLES59SZ4d6hVOPCSf80Bg==";
      };
    };
    "@formatjs/intl-localematcher-0.2.25" = {
      name = "_at_formatjs_slash_intl-localematcher";
      packageName = "@formatjs/intl-localematcher";
      version = "0.2.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/@formatjs/intl-localematcher/-/intl-localematcher-0.2.25.tgz";
        sha512 = "YmLcX70BxoSopLFdLr1Ds99NdlTI2oWoLbaUW2M406lxOIPzE1KQhRz2fPUkq34xVZQaihCoU29h0KK7An3bhA==";
      };
    };
    "@material/animation-14.0.0" = {
      name = "_at_material_slash_animation";
      packageName = "@material/animation";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/animation/-/animation-14.0.0.tgz";
        sha512 = "VlYSfUaIj/BBVtRZI8Gv0VvzikFf+XgK0Zdgsok5c1v5DDnNz5tpB8mnGrveWz0rHbp1X4+CWLKrTwNmjrw3Xw==";
      };
    };
    "@material/base-14.0.0" = {
      name = "_at_material_slash_base";
      packageName = "@material/base";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/base/-/base-14.0.0.tgz";
        sha512 = "Ou7vS7n1H4Y10MUZyYAbt6H0t67c6urxoCgeVT7M38aQlaNUwFMODp7KT/myjYz2YULfhu3PtfSV3Sltgac9mA==";
      };
    };
    "@material/button-14.0.0" = {
      name = "_at_material_slash_button";
      packageName = "@material/button";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/button/-/button-14.0.0.tgz";
        sha512 = "dqqHaJq0peyXBZupFzCjmvScrfljyVU66ZCS3oldsaaj5iz8sn33I/45Z4zPzdR5F5z8ExToHkRcXhakj1UEAA==";
      };
    };
    "@material/density-14.0.0" = {
      name = "_at_material_slash_density";
      packageName = "@material/density";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/density/-/density-14.0.0.tgz";
        sha512 = "NlxXBV5XjNsKd8UXF4K/+fOXLxoFNecKbsaQO6O2u+iG8QBfFreKRmkhEBb2hPPwC3w8nrODwXX0lHV+toICQw==";
      };
    };
    "@material/dom-14.0.0" = {
      name = "_at_material_slash_dom";
      packageName = "@material/dom";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/dom/-/dom-14.0.0.tgz";
        sha512 = "8t88XyacclTj8qsIw9q0vEj4PI2KVncLoIsIMzwuMx49P2FZg6TsLjor262MI3Qs00UWAifuLMrhnOnfyrbe7Q==";
      };
    };
    "@material/elevation-14.0.0" = {
      name = "_at_material_slash_elevation";
      packageName = "@material/elevation";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/elevation/-/elevation-14.0.0.tgz";
        sha512 = "Di3tkxTpXwvf1GJUmaC8rd+zVh5dB2SWMBGagL4+kT8UmjSISif/OPRGuGnXs3QhF6nmEjkdC0ijdZLcYQkepw==";
      };
    };
    "@material/feature-targeting-14.0.0" = {
      name = "_at_material_slash_feature-targeting";
      packageName = "@material/feature-targeting";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/feature-targeting/-/feature-targeting-14.0.0.tgz";
        sha512 = "a5WGgHEq5lJeeNL5yevtgoZjBjXWy6+klfVWQEh8oyix/rMJygGgO7gEc52uv8fB8uAIoYEB3iBMOv8jRq8FeA==";
      };
    };
    "@material/focus-ring-14.0.0" = {
      name = "_at_material_slash_focus-ring";
      packageName = "@material/focus-ring";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/focus-ring/-/focus-ring-14.0.0.tgz";
        sha512 = "fqqka6iSfQGJG3Le48RxPCtnOiaLGPDPikhktGbxlyW9srBVMgeCiONfHM7IT/1eu80O0Y67Lh/4ohu5+C+VAQ==";
      };
    };
    "@material/ripple-14.0.0" = {
      name = "_at_material_slash_ripple";
      packageName = "@material/ripple";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/ripple/-/ripple-14.0.0.tgz";
        sha512 = "9XoGBFd5JhFgELgW7pqtiLy+CnCIcV2s9cQ2BWbOQeA8faX9UZIDUx/g76nHLZ7UzKFtsULJxZTwORmsEt2zvw==";
      };
    };
    "@material/rtl-14.0.0" = {
      name = "_at_material_slash_rtl";
      packageName = "@material/rtl";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/rtl/-/rtl-14.0.0.tgz";
        sha512 = "xl6OZYyRjuiW2hmbjV2omMV8sQtfmKAjeWnD1RMiAPLCTyOW9Lh/PYYnXjxUrNa0cRwIIbOn5J7OYXokja8puA==";
      };
    };
    "@material/shape-14.0.0" = {
      name = "_at_material_slash_shape";
      packageName = "@material/shape";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/shape/-/shape-14.0.0.tgz";
        sha512 = "o0mJB0+feOv473KckI8gFnUo8IQAaEA6ynXzw3VIYFjPi48pJwrxa0mZcJP/OoTXrCbDzDeFJfDPXEmRioBb9A==";
      };
    };
    "@material/theme-14.0.0" = {
      name = "_at_material_slash_theme";
      packageName = "@material/theme";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/theme/-/theme-14.0.0.tgz";
        sha512 = "6/SENWNIFuXzeHMPHrYwbsXKgkvCtWuzzQ3cUu4UEt3KcQ5YpViazIM6h8ByYKZP8A9d8QpkJ0WGX5btGDcVoA==";
      };
    };
    "@material/tokens-14.0.0" = {
      name = "_at_material_slash_tokens";
      packageName = "@material/tokens";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/tokens/-/tokens-14.0.0.tgz";
        sha512 = "SXgB9VwsKW4DFkHmJfDIS0x0cGdMWC1D06m6z/WQQ5P5j6/m0pKrbHVlrLzXcRjau+mFhXGvj/KyPo9Pp/Rc8Q==";
      };
    };
    "@material/touch-target-14.0.0" = {
      name = "_at_material_slash_touch-target";
      packageName = "@material/touch-target";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/touch-target/-/touch-target-14.0.0.tgz";
        sha512 = "o3kvxmS4HkmZoQTvtzLJrqSG+ezYXkyINm3Uiwio1PTg67pDgK5FRwInkz0VNaWPcw9+5jqjUQGjuZMtjQMq8w==";
      };
    };
    "@material/typography-14.0.0" = {
      name = "_at_material_slash_typography";
      packageName = "@material/typography";
      version = "14.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/typography/-/typography-14.0.0.tgz";
        sha512 = "/QtHBYiTR+TPMryM/CT386B2WlAQf/Ae32V324Z7P40gHLKY/YBXx7FDutAWZFeOerq/two4Nd2aAHBcMM2wMw==";
      };
    };
    "anymatch-3.1.3" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.3.tgz";
        sha512 = "KMReFUr0B4t+D+OBkjR3KYqvocp2XaSzO55UcB6mgQMd3KbcE+mWTyvVV7D/zsdEbNnV6acZUutkiHQXvTr1Rw==";
      };
    };
    "binary-extensions-2.3.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.3.0.tgz";
        sha512 = "Ceh+7ox5qe7LJuLHoY0feh3pHuUDHAcRUeyL2VYghZwfpkNIy/+8Ocg0a3UuSoYzavmylwuLWQOf3hl0jjMMIw==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "chokidar-3.6.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-3.6.0.tgz";
        sha512 = "7VT13fmjotKpGipCW9JEQAusEPE+Ei8nl6/g4FBAmIm0GOOLMua9NDDo/DWp0ZAxCr3cPq5ZpBqmPAQgDda2Pw==";
      };
    };
    "cli-color-2.0.4" = {
      name = "cli-color";
      packageName = "cli-color";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-color/-/cli-color-2.0.4.tgz";
        sha512 = "zlnpg0jNcibNrO7GG9IeHH7maWFeCz+Ja1wx/7tZNU5ASSSSZ+/qZciM0/LHCYxSdqv5h2sdbQ/PXYdOuetXvA==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "d-1.0.2" = {
      name = "d";
      packageName = "d";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d/-/d-1.0.2.tgz";
        sha512 = "MOqHvMWF9/9MX6nza0KgvFH4HpMU0EF5uUDXqX/BtxtU8NfB0QzRtJ8Oe/6SuS4kbhyzVJwjd97EA4PKrzJ8bw==";
      };
    };
    "d3-array-1.2.4" = {
      name = "d3-array";
      packageName = "d3-array";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-array/-/d3-array-1.2.4.tgz";
        sha512 = "KHW6M86R+FUPYGb3R5XiYjXPq7VzwxZ22buHhAEVG5ztoEcZZMLov530mmccaqA1GghZArjQV46fuc8kUqhhHw==";
      };
    };
    "d3-polygon-1.0.6" = {
      name = "d3-polygon";
      packageName = "d3-polygon";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-polygon/-/d3-polygon-1.0.6.tgz";
        sha512 = "k+RF7WvI08PC8reEoXa/w2nSg5AUMTi+peBD9cmFc+0ixHfbs4QmxxkarVal1IkVkgxVuk9JSHhJURHiyHKAuQ==";
      };
    };
    "deepmerge-4.3.1" = {
      name = "deepmerge";
      packageName = "deepmerge";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deepmerge/-/deepmerge-4.3.1.tgz";
        sha512 = "3sUqbMEc77XqpdNO7FRyRog+eW3ph+GYCbj+rK+uYyRMuwsVy0rMiVtPn+QJlKFvWP/1PYpapqYn0Me2knFn+A==";
      };
    };
    "earcut-2.2.4" = {
      name = "earcut";
      packageName = "earcut";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/earcut/-/earcut-2.2.4.tgz";
        sha512 = "/pjZsA1b4RPHbeWZQn66SWS8nZZWLQQ23oE3Eam7aroEFGEvwKAsJfZ9ytiEMycfzXWpca4FA9QIOehf7PocBQ==";
      };
    };
    "es5-ext-0.10.64" = {
      name = "es5-ext";
      packageName = "es5-ext";
      version = "0.10.64";
      src = fetchurl {
        url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.64.tgz";
        sha512 = "p2snDhiLaXe6dahss1LddxqEm+SkuDvV8dnIQG0MWjyHpcMNfXKPE+/Cc0y+PhxJX3A4xGNeFCj5oc0BUh6deg==";
      };
    };
    "es6-iterator-2.0.3" = {
      name = "es6-iterator";
      packageName = "es6-iterator";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.3.tgz";
        sha512 = "zw4SRzoUkd+cl+ZoE15A9o1oQd920Bb0iOJMQkQhl3jNc03YqVjAhG7scf9C5KWRU/R13Orf588uCC6525o02g==";
      };
    };
    "es6-symbol-3.1.4" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "3.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.4.tgz";
        sha512 = "U9bFFjX8tFiATgtkJ1zg25+KviIXpgRvRHS8sau3GfhVzThRQrOeksPeT0BWW2MNZs1OEWJ1DPXOQMn0KKRkvg==";
      };
    };
    "es6-weak-map-2.0.3" = {
      name = "es6-weak-map";
      packageName = "es6-weak-map";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-weak-map/-/es6-weak-map-2.0.3.tgz";
        sha512 = "p5um32HOTO1kP+w7PRnB+5lQ43Z6muuMuIMffvDN8ZB4GcnjLBV6zGStpbASIMk4DCAvEaamhe2zhyCb/QXXsA==";
      };
    };
    "esbuild-0.19.12" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.19.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.19.12.tgz";
        sha512 = "aARqgq8roFBj054KvQr5f1sFu0D65G+miZRCuJyJ0G13Zwx7vRar5Zhn2tkQNzIXcBrNVsv/8stehpj+GAjgbg==";
      };
    };
    "esniff-2.0.1" = {
      name = "esniff";
      packageName = "esniff";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esniff/-/esniff-2.0.1.tgz";
        sha512 = "kTUIGKQ/mDPFoJ0oVfcmyJn4iBDRptjNVIzwIFR7tqWXdVI9xfA2RMwY/gbSpJG3lkdWNEjLap/NqVHZiJsdfg==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "event-emitter-0.3.5" = {
      name = "event-emitter";
      packageName = "event-emitter";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-emitter/-/event-emitter-0.3.5.tgz";
        sha512 = "D9rRn9y7kLPnJ+hMq7S/nhvoKwwvVJahBi2BPmx3bvbsEdK3W9ii8cBSGjP+72/LnM4n6fo3+dkCX5FeTQruXA==";
      };
    };
    "ext-1.7.0" = {
      name = "ext";
      packageName = "ext";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ext/-/ext-1.7.0.tgz";
        sha512 = "6hxeJYaL110a9b5TEJSj0gojyHQAmA2ch5Os+ySCiA1QGdS697XWY1pzsrSjqA9LDEEgdB/KypIlR59RcLuHYw==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "flubber2-0.4.9" = {
      name = "flubber2";
      packageName = "flubber2";
      version = "0.4.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/flubber2/-/flubber2-0.4.9.tgz";
        sha512 = "rIaVuPbsZmlPhnL759wc3ffd1j2lpUQlsmhC2lgRVOJFCiFlsvyXdT9Mc6mqMCkXnVElvVpsavsJdwvIEjK5CA==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "globalyzer-0.1.0" = {
      name = "globalyzer";
      packageName = "globalyzer";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globalyzer/-/globalyzer-0.1.0.tgz";
        sha512 = "40oNTM9UfG6aBmuKxk/giHn5nQ8RVz/SS4Ir6zgzOv9/qC3kKZ9v4etGTcJbEl/NyVQH7FGU7d+X1egr57Md2Q==";
      };
    };
    "globrex-0.1.2" = {
      name = "globrex";
      packageName = "globrex";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/globrex/-/globrex-0.1.2.tgz";
        sha512 = "uHJgbwAMwNFf5mLst7IWLNg14x1CkeqglJb/K3doi4dw6q2IvAAmM/Y81kevy83wP+Sst+nutFTYOGg3d1lsxg==";
      };
    };
    "immutable-4.3.5" = {
      name = "immutable";
      packageName = "immutable";
      version = "4.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-4.3.5.tgz";
        sha512 = "8eabxkth9gZatlwl5TBuJnCsoTADlL6ftEr7A4qgdaTsPyreilDSnUk57SO+jfKcNtxPa22U5KK6DSeAYhpBJw==";
      };
    };
    "intl-messageformat-9.13.0" = {
      name = "intl-messageformat";
      packageName = "intl-messageformat";
      version = "9.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/intl-messageformat/-/intl-messageformat-9.13.0.tgz";
        sha512 = "7sGC7QnSQGa5LZP7bXLDhVDtQOeKGeBFGHF2Y8LVBwYZoQZCgWeKoPGTa5GMG8g/TzDgeXuYJQis7Ggiw2xTOw==";
      };
    };
    "is-binary-path-2.1.0" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
        sha512 = "ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-promise-2.2.2" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-2.2.2.tgz";
        sha512 = "+lP4/6lKUBfQjZ2pdxThZvLUAafmZb8OAxFb8XXtiQmS35INgr85hdOGoEs124ez1FCnZJt6jau/T+alh58QFQ==";
      };
    };
    "lru-queue-0.1.0" = {
      name = "lru-queue";
      packageName = "lru-queue";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-queue/-/lru-queue-0.1.0.tgz";
        sha512 = "BpdYkt9EvGl8OfWHDQPISVpcl5xZthb+XPsbELj5AQXxIC8IriDZIQYjBJPEm5rS420sjZ0TLEzRcq5KdBhYrQ==";
      };
    };
    "memoizee-0.4.15" = {
      name = "memoizee";
      packageName = "memoizee";
      version = "0.4.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/memoizee/-/memoizee-0.4.15.tgz";
        sha512 = "UBWmJpLZd5STPm7PMUlOw/TSy972M+z8gcyQ5veOnSDRREz/0bmpyTfKt3/51DhEBqCZQn1udM/5flcSPYhkdQ==";
      };
    };
    "mri-1.2.0" = {
      name = "mri";
      packageName = "mri";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mri/-/mri-1.2.0.tgz";
        sha512 = "tzzskb3bG8LvYGFF/mDTpq3jpI6Q9wc3LEmBaghu+DdCssd1FakN7Bc0hVNmEyGq1bq3RgfkCb3cmQLpNPOroA==";
      };
    };
    "next-tick-1.1.0" = {
      name = "next-tick";
      packageName = "next-tick";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/next-tick/-/next-tick-1.1.0.tgz";
        sha512 = "CXdUiJembsNjuToQvxayPZF9Vqht7hewsvy2sOWafLvi2awflj9mOC6bHIg50orX8IJvWKY9wYQ/zB2kogPslQ==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "readdirp-3.6.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-3.6.0.tgz";
        sha512 = "hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==";
      };
    };
    "sade-1.8.1" = {
      name = "sade";
      packageName = "sade";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sade/-/sade-1.8.1.tgz";
        sha512 = "xal3CZX1Xlo/k4ApwCFrHVACi9fBqJ7V+mwhBsuf/1IOKbBy098Fex+Wa/5QMubw09pSZ/u8EY8PWgevJsXp1A==";
      };
    };
    "sass-1.72.0" = {
      name = "sass";
      packageName = "sass";
      version = "1.72.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass/-/sass-1.72.0.tgz";
        sha512 = "Gpczt3WA56Ly0Mn8Sl21Vj94s1axi9hDIzDFn9Ph9x3C3p4nNyvsqJoQyVXKou6cBlfFWEgRW4rT8Tb4i3XnVA==";
      };
    };
    "source-map-js-1.2.0" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.0.tgz";
        sha512 = "itJW8lvSA0TXEphiRoawsCksnlf8SyvmFzIhltqAHluXd88pkCd+cXJVHTDwdCr0IzwptSm035IHQktUu1QUMg==";
      };
    };
    "svelte-glitch-0.0.3" = {
      name = "svelte-glitch";
      packageName = "svelte-glitch";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte-glitch/-/svelte-glitch-0.0.3.tgz";
        sha512 = "WiDKUR9XIXIoJS6kOdjkvDc6jPpAWOq+6XyNb+6CzjbDIXhIcQPGYVAdYAkh0eMzgSL7y9kjjCmhGrWfrTEr1A==";
      };
    };
    "svelte-i18n-3.7.4" = {
      name = "svelte-i18n";
      packageName = "svelte-i18n";
      version = "3.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte-i18n/-/svelte-i18n-3.7.4.tgz";
        sha512 = "yGRCNo+eBT4cPuU7IVsYTYjxB7I2V8qgUZPlHnNctJj5IgbJgV78flsRzpjZ/8iUYZrS49oCt7uxlU3AZv/N5Q==";
      };
    };
    "svelte-navbar-0.0.122" = {
      name = "svelte-navbar";
      packageName = "svelte-navbar";
      version = "0.0.122";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte-navbar/-/svelte-navbar-0.0.122.tgz";
        sha512 = "sUkzuYsXWcuYPZKdRDVb68RjeQMHNwiGwC5y0+yb931XPVBsKbLtCxhOTQjp9xDMz+7SikKLwWs1qZ+ygjgQfA==";
      };
    };
    "svelte-scrolling-plus-1.2.3" = {
      name = "svelte-scrolling-plus";
      packageName = "svelte-scrolling-plus";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte-scrolling-plus/-/svelte-scrolling-plus-1.2.3.tgz";
        sha512 = "XshtYIzw/ot8nxuVK3+bMOmFhU2ovGEzrxhd19bmKZBBr7MkWxo1r3TqvmpY5OlWf8W1rTlYIRGUJwwwlGrwiQ==";
      };
    };
    "svelte-vertical-timeline-0.0.2" = {
      name = "svelte-vertical-timeline";
      packageName = "svelte-vertical-timeline";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte-vertical-timeline/-/svelte-vertical-timeline-0.0.2.tgz";
        sha512 = "tM+wghFsIW3Xb/KC+ImlTw1S1THTEhcVki8x4/u+XVLGAnRGiPbeiO/aRhVj0k8v7D8YZHwlRm0X295KyAKQdg==";
      };
    };
    "svg-path-properties-0.2.2" = {
      name = "svg-path-properties";
      packageName = "svg-path-properties";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg-path-properties/-/svg-path-properties-0.2.2.tgz";
        sha512 = "GmrB+b6woz6CCdQe6w1GHs/1lt25l7SR5hmhF8jRdarpv/OgjLyuQygLu1makJapixeb1aQhP/Oa1iKi93o/aQ==";
      };
    };
    "svgpath-2.6.0" = {
      name = "svgpath";
      packageName = "svgpath";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgpath/-/svgpath-2.6.0.tgz";
        sha512 = "OIWR6bKzXvdXYyO4DK/UWa1VA1JeKq8E+0ug2DG98Y/vOmMpfZNj+TIG988HjfYSqtcy/hFOtZq/n/j5GSESNg==";
      };
    };
    "timers-ext-0.1.7" = {
      name = "timers-ext";
      packageName = "timers-ext";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/timers-ext/-/timers-ext-0.1.7.tgz";
        sha512 = "b85NUNzTSdodShTIbky6ZF02e8STtVVfD+fu4aXXShEELpozH+bCpJLYMPZbsABN2wDH7fJpqIoXxJpzbf0NqQ==";
      };
    };
    "tiny-glob-0.2.9" = {
      name = "tiny-glob";
      packageName = "tiny-glob";
      version = "0.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-glob/-/tiny-glob-0.2.9.tgz";
        sha512 = "g/55ssRPUjShh+xkfx9UPDXqhckHEsHr4Vd9zX55oSdGZc/MD0m3sferOkwWtp98bv+kcVfEHtRJgBVJzelrzg==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "topojson-client-3.1.0" = {
      name = "topojson-client";
      packageName = "topojson-client";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/topojson-client/-/topojson-client-3.1.0.tgz";
        sha512 = "605uxS6bcYxGXw9qi62XyrV6Q3xwbndjachmNxu8HWTtVPxZfEJN9fd/SZS1Q54Sn2y0TMyMxFj/cJINqGHrKw==";
      };
    };
    "tslib-2.6.2" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.6.2.tgz";
        sha512 = "AEYxH93jGFPn/a2iVAwW87VuUIkR1FVUKB77NwMF7nBTDkDrrT/Hpt/IrCJ0QXhW27jTBDcf5ZY7w6RiqTMw2Q==";
      };
    };
    "type-2.7.2" = {
      name = "type";
      packageName = "type";
      version = "2.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type/-/type-2.7.2.tgz";
        sha512 = "dzlvlNlt6AXU7EBSfpAscydQ7gXB+pPGsPnfJnZpiNJBDj7IaJzQlBZYGdEi4R9HmPdBv2XmWJ6YUtoTa7lmCw==";
      };
    };
    "typescript-4.9.5" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.9.5.tgz";
        sha512 = "1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g==";
      };
    };
  };
  args = {
    name = "hannesgith.github.io";
    packageName = "hannesgith.github.io";
    version = "0.0.2";
    src = ./.;
    dependencies = [
      sources."@formatjs/ecma402-abstract-1.11.4"
      sources."@formatjs/fast-memoize-1.2.1"
      sources."@formatjs/icu-messageformat-parser-2.1.0"
      sources."@formatjs/icu-skeleton-parser-1.3.6"
      sources."@formatjs/intl-localematcher-0.2.25"
      sources."@material/animation-14.0.0"
      sources."@material/base-14.0.0"
      sources."@material/button-14.0.0"
      sources."@material/density-14.0.0"
      sources."@material/dom-14.0.0"
      sources."@material/elevation-14.0.0"
      sources."@material/feature-targeting-14.0.0"
      sources."@material/focus-ring-14.0.0"
      sources."@material/ripple-14.0.0"
      sources."@material/rtl-14.0.0"
      sources."@material/shape-14.0.0"
      sources."@material/theme-14.0.0"
      sources."@material/tokens-14.0.0"
      sources."@material/touch-target-14.0.0"
      sources."@material/typography-14.0.0"
      sources."anymatch-3.1.3"
      sources."binary-extensions-2.3.0"
      sources."braces-3.0.2"
      sources."chokidar-3.6.0"
      sources."cli-color-2.0.4"
      sources."commander-2.20.3"
      sources."d-1.0.2"
      sources."d3-array-1.2.4"
      sources."d3-polygon-1.0.6"
      sources."deepmerge-4.3.1"
      sources."earcut-2.2.4"
      sources."es5-ext-0.10.64"
      sources."es6-iterator-2.0.3"
      sources."es6-symbol-3.1.4"
      sources."es6-weak-map-2.0.3"
      sources."esbuild-0.19.12"
      sources."esniff-2.0.1"
      sources."estree-walker-2.0.2"
      sources."event-emitter-0.3.5"
      sources."ext-1.7.0"
      sources."fill-range-7.0.1"
      sources."flubber2-0.4.9"
      sources."glob-parent-5.1.2"
      sources."globalyzer-0.1.0"
      sources."globrex-0.1.2"
      sources."immutable-4.3.5"
      sources."intl-messageformat-9.13.0"
      sources."is-binary-path-2.1.0"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."is-promise-2.2.2"
      sources."lru-queue-0.1.0"
      sources."memoizee-0.4.15"
      sources."mri-1.2.0"
      sources."next-tick-1.1.0"
      sources."normalize-path-3.0.0"
      sources."picomatch-2.3.1"
      sources."readdirp-3.6.0"
      sources."sade-1.8.1"
      sources."sass-1.72.0"
      sources."source-map-js-1.2.0"
      sources."svelte-glitch-0.0.3"
      sources."svelte-i18n-3.7.4"
      sources."svelte-navbar-0.0.122"
      sources."svelte-scrolling-plus-1.2.3"
      sources."svelte-vertical-timeline-0.0.2"
      sources."svg-path-properties-0.2.2"
      sources."svgpath-2.6.0"
      sources."timers-ext-0.1.7"
      sources."tiny-glob-0.2.9"
      sources."to-regex-range-5.0.1"
      sources."topojson-client-3.1.0"
      sources."tslib-2.6.2"
      sources."type-2.7.2"
      sources."typescript-4.9.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
