on:
  #pull_request: #ODO: remove
  push:
    branches:
      - staging
      - release

name: Release

jobs:

  build:
    runs-on: ubuntu-latest
    name: ssg 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v3
      - run: npm i
      - run: npm run build
      - name: upload build folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: static
          path: ./build

  deploy-web:
    needs: [build]
    name: Deploy Web-App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # no idea why but apperently this creates a folder structure (i dont need my repo to be checked out tho)
      - name: download web artifact
        uses: actions/download-artifact@v2
        with:
          name: static
          path: static
      
      - run: touch static/.nojekyll # this is needed to prevent github pages from ignoring files starting with an underscore
      - run: touch CNAME && echo 'cv.h-h.win' >> CNAME
      - run: |
           mkdir static/.well-known && touch static/.well-known/assetlinks.json
           echo '[{"relation": ["delegate_permission/common.handle_all_urls"], "target": { "namespace": "android_app","package_name": "hannepps.tools.passwordchecker","sha256_cert_fingerprints": ["48:8D:7C:D4:BA:57:9C:72:95:CF:DE:7D:C0:E2:2B:0B:EC:89:B5:01:78:88:12:C4:44:D6:D4:31:97:52:73:8E"]}}]' >> static/.well-known/assetlinks.json
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: static
