on:
  #pull_request: #ODO: remove
  push:
    branches:
      - staging
      - release

name: Release

jobs:

  build:
    runs-on: ubuntu-latest
    name: ssg 
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: hannesgith
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community, cachix
      - name: build
        run: | 
          nix build -L --show-trace
          cp -r result/build build
      - name: upload build folder as artifact
        uses: actions/upload-artifact@v7
        with:
          name: static
          path: ./build

  deploy-web:
    needs: [build]
    name: Deploy Web-App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7 # no idea why but apperently this creates a folder structure (i dont need my repo to be checked out tho)
      - name: download web artifact
        uses: actions/download-artifact@v8
        with:
          name: static
          path: static
      
      - run: touch static/.nojekyll # this is needed to prevent github pages from ignoring files starting with an underscore
      - run: echo 'cv.h-h.win' > static/CNAME # must be inside the deployed folder
      - run: |
           mkdir static/.well-known && touch static/.well-known/assetlinks.json
           echo '[{"relation": ["delegate_permission/common.handle_all_urls"], "target": { "namespace": "android_app","package_name": "hannepps.tools.passwordchecker","sha256_cert_fingerprints": ["48:8D:7C:D4:BA:57:9C:72:95:CF:DE:7D:C0:E2:2B:0B:EC:89:B5:01:78:88:12:C4:44:D6:D4:31:97:52:73:8E"]}}]' >> static/.well-known/assetlinks.json
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          branch: gh-pages
          folder: static
